In [3]:
#Write a Python program to find the sum of all elements in a list using loop.
#Input:- [10,20,30,40]
# #Output:- 100
#using "Sum"
# myList=[23,4,2,6,7]
 
# print(sum(myList))

#using "Loop"

myList=[23,4,2,6,7]
 
def sumOfList(myList):
    nSum=0
    for i in myList:
        nSum+=i
    return nSum
         
print(sumOfList(myList))

42


In [1]:
#Write a Python program to find the multiplication of all elements in a list using loop.
#Input:- [10,20,30,40]
#Output:- 240000
# def multiply(numbers):  
#     total = 1
#     for x in numbers:
#         total *= x  
#     return total  
# print(multiply((8, 2, 3, -1, 7)))
# def multiply( array , n ): 
#     pro = 1
#     for i in range(n): 
#         pro = pro * array[i] 
#     return pro 
# my_list=[]
# for i in range(1,5):
#     my_list.append(i)
#     print(my_list)
#     result=1
#     for item in my_list:
#         result=result*item
#     print("Multiplication= ", result)

lst=[10,20,30,40]
lst_mult=1
for num in lst:
    lst_mult*=num
print("Multiplication of all the elements in the list is : ", lst_mult)

Multiplication of all the elements in the list is :  240000


In [2]:
#Write a Python program to find the largest number from a list using loop.
#Input:- [10,100,2321, 1,200,2]
#Output:- 2321

lst=[10,100,2321,1,200,2]
num=0
for i in range(len(lst)):
    if num<lst[i]:
        num=lst[i]
print("the largest number in the list is : ", num)

the largest number in the list is :  2321


In [6]:
#Write a Python program to find the smallest number from a list using loop.
#Input:- [10,100,2321, 1,200,2]
#Output:- 1
lst=[10,100,2321,1,200,2]
num=500000000000000000
for i in range(len(lst)):
    if num>lst[i]:
        num=lst[i]
print("the smallest number in the list is : ", num)

the smallest number in the list is :  1


In [14]:
#Write a Python program to count the number of strings having length more than 2 and are palindrome in a list using loop.
#Input:- ['ab', 'abc', 'aba', 'xyz', '1991']
#Output:- 2
lst = ['ab', 'abc', 'aba', 'xyz', '1991']
count_palindrome = 0
for i in lst:
    if len(i) > 2 and i == i[::-1]:
        count_palindrome += 1
print(f'The total number of palindrome elements are {count_palindrome}')



The total number of palindrome elements are 2


In [9]:
#Write a Python program to sort a list in ascending order using loop.
#Input:- [100,10,1,298,65,483,49876,2,80,9,9213]
#Output:- [1,2,9,10,65,80,100,298,483,9213,49876]
lst=[100,10,1,298,65,483,49876,2,80,9,9213]

for i in range(len(lst)):
    for j in range(i+1,len(lst)):
        if lst[i]>lst[j]:
            a=lst[i]
            lst[i]=lst[j]
            lst[j]=a
print(lst)





[1, 2, 9, 10, 65, 80, 100, 298, 483, 9213, 49876]


In [12]:
#Write a Python program to get a sorted list in increasing order of last element in each tuple in a given list using loop.
#Input:- [(5,4),(9,1),(2,3),(5,9),(7,6),(5,5)]
#output:- [(9,1),(2,3),(5,4),(5,5),(7,6),(5,9)]

lst = [(5,4),(9,1),(2,3),(5,9),(7,6),(5,5)]
new=[]
new1=[]
for i in range(len(lst)):
    a=lst[i][1]
    b=lst[i][0]
    tup=(a,b)
    new.append(tup)
new.sort()
for j in range(len(new)):
    c=new[j][1]
    d=new[j][0]
    tup1=(c,d)
    new1.append(tup1)
print(new1)


[(9, 1), (2, 3), (5, 4), (5, 5), (7, 6), (5, 9)]


In [13]:
#Write a Python program to remove duplicate element from a list using loop.
#Input:- [10,1,11,1,29,876,768,10,11,1,92,29,876]
#Output:- [10,1,11,29,876,768,92]
lst=[10,1,11,1,29,876,768,10,11,1,92,29,876]
a=[]
for num in lst:
    if num not in a:
        a.append(num)
print("output: ", a)


output:  [10, 1, 11, 29, 876, 768, 92]


In [14]:
#Write a Python program to check a list is empty or not?
#Input:- []
#Output:- List is empty
#Input:- [10,20,30]
#Output:- List is not empty

lst=eval(input('enter a list: '))
print(lst)
if len(lst)==0:
    print("list is empty")
else:
    print("list is not empty")


enter a list: 50,60,40
(50, 60, 40)
list is not empty


In [16]:
#Write a Python program to copy a list using loop.
#inp_lst = [10,10.20,10+20j, 'Python', [10,20], (10,20)]
#out_lst = [10,10.20,10+20j, 'Python', [10,20], (10,20)]


inp_lst = [10,10.20,10+20j, 'Python', [10,20], (10,20)]
new=[]
for i in inp_lst:
    new.append(i)
print("Copy of list inp_lst: ", new)



Copy of list inp_lst:  [10, 10.2, (10+20j), 'Python', [10, 20], (10, 20)]


In [17]:
#Write a Python program to find the list of words that are longer than or equal to 4 from a given string.
#Input:- 'How much wood would a woodchuck chuck if a woodchuck could chuck wood'
#Output:- ['much', 'wood', 'would', 'woodchuck', 'chuck', 'could', 'could']
#Note:- Duplicate should be avoided.

string='How much wood would a woodchuck chuck if a woodchuck could chuck wood'

lst=string.split()
i=0
new=[]
for word in lst:
    n=len(lst[i])
    i+=1
    if n>=4 and word not in new:
        new.append(word)
print("output:", new)




output: ['much', 'wood', 'would', 'woodchuck', 'chuck', 'could']


In [18]:
#Write a Python program which takes two list as input and returns True if they have at least 3 common elements.
#inp_lst1 = [10,20,'Python', 10.20, 10+20j, [10,20,30], (10,20,30)]
#inp_lst2 = [(10,20,30),1,20+3j,100.2, 10+20j, [10,20,30],'Python']
#Output:- True

inp_lst1 = [10,20,'Python', 10.20, 10+20j, [10,20,30], (10,20,30)]
inp_lst2 = [(10,20,30),1,20+3j,100.2, 10+20j, [10,20,30],'Python']

from copy import deepcopy
a_deep=deepcopy(lst)
for num in inp_lst1:
    if num in a_deep:
        a_deep.append(num)
for num in inp_lst2:
    if num in a_deep:
        a_deep.remove(num)
if len(a_deep)>=3:
    print("output: ", True)
else:
    print("Output: ", False)


output:  True


In [20]:
#Write a Python program to create a 4X4 2D matrix with below elements using loop and list comprehension both.
#Output:- [[0,0,0,0],[0,1,2,3],[0,2,4,6],[0,3,6,9]]
#Write a Python program to create a 4X4 2D matrix with below elements using loop and list comprehension both.
# [[0,0,0,0],[0,1,2,3],[0,2,4,6],[0,3,6,9]]
# [[],[],[],[]]


# Using Loop
out_lst = []
for i in range(4):
    in_lst =[]
    i+=1
    j=0
    for j in range(4):
        in_lst.append((i-1)*j)
        j+=1
    out_lst.append(in_lst)
print(out_lst)


# i = 0
# out_lst = []
# in_lst = []

# i = 0
# j = 0
# out_lst = []
# in_lst = [0]

# i = 0
# j = 1
# out_lst = []
# in_lst = [0,0]

# i = 0
# j = 2
# out_lst = []
# in_lst = [0,0,0]

# i = 0
# j = 3
# in_lst = [0,0,0,0]
# out_lst = [[0,0,0,0]]

# i = 1
# j = 0
# in_lst = [0]
# out_lst = [[0,0,0,0]]

# i = 1
# j = 1
# in_lst = [0,1]
# out_lst = [[0,0,0,0]]

# i = 1
# j = 2
# in_lst = [0,1,2]
# out_lst = [[0,0,0,0]]

# i = 1
# j = 3
# in_lst = [0,1,2,3]
# out_lst = [[0,0,0,0],[0,1,2,3]]

# Using Loop comprehension
# [[i*j for j in range(4)] for i in range(4)]

# [i**2 for i in range(4)]

#Write a Python program to create a 3X4X6 3D matrix wiith below elements using loop

# Using Loop
# out_lst = []
# for i in range(3):
#     in_lst1 =[]
#     for j in range(4):
#         in_lst2 = []
#         for k in range(6):
#             in_lst2.append(i*j)
#         in_lst1.append(in_lst2)
#     out_lst.append(in_lst1)
# print(out_lst)



#     [[[0,0,0,0,0,0],[0,0,0,0,0,0],[0,0,0,0,0,0],[0,0,0,0,0,0]],
#     [[0,0,0,0,0,0],[1,1,1,1,1,1],[2,2,2,2,2,2],[3,3,3,3,3,3]],
#     [[0,0,0,0,0,0],[2,2,2,2,2,2],[4,4,4,4,4,4],[6,6,6,6,6,6]]]

# Using Loop comprehension
[[[i*j for k in range(6)]for j in range(4)]for i in range(3)]


[[0, 0, 0, 0], [0, 1, 2, 3], [0, 2, 4, 6], [0, 3, 6, 9]]


[[[0, 0, 0, 0, 0, 0],
  [0, 0, 0, 0, 0, 0],
  [0, 0, 0, 0, 0, 0],
  [0, 0, 0, 0, 0, 0]],
 [[0, 0, 0, 0, 0, 0],
  [1, 1, 1, 1, 1, 1],
  [2, 2, 2, 2, 2, 2],
  [3, 3, 3, 3, 3, 3]],
 [[0, 0, 0, 0, 0, 0],
  [2, 2, 2, 2, 2, 2],
  [4, 4, 4, 4, 4, 4],
  [6, 6, 6, 6, 6, 6]]]

In [ ]:
#Write a Python program to create a 3X4X6 3D matrix wiith below elements using loop
#Output:- 
# [
#     [[0,0,0,0,0,0],[0,0,0,0,0,0],[0,0,0,0,0,0],[0,0,0,0,0,0]],
#     [[0,0,0,0,0,0],[1,1,1,1,1,1],[2,2,2,2,2,2],[3,3,3,3,3,3]],
#     [[0,0,0,0,0,0],[2,2,2,2,2,2],[4,4,4,4,4,4],[6,6,6,6,6,6]]
# ]

In [24]:
#Write a Python program which takes a list of numbers as input and prints a new list after removing even numbers from it.
#Input:- [10,21,22,98,87,45,33,1,2,100]
#Output:- [21,87,45,33,1]

Inp = [10,21,22,98,87,45,33,1,2,100]
new=[]
for num in Inp:
    if num%2!=0 and num not in new:
        new.append(num)
print("New List: ", new)



New List:  [21, 87, 45, 33, 1]


In [26]:
#Write a Python program which takes a list from the user and prints it after reshuffling the elements of the list.
#Input:- [10,21,22,98,87,45,33,1,2,100]
#Output:- [1,87,21,10,33,2,100,45,98,22] (It may be any randon list but with same elements)


#inp=[10,21,22,98,87,45,33,1,2,100]
lst=eval(input("Enter a list: "))

from random import shuffle
shuffle(lst)
print("Output: ", lst)






Enter a list: [10,21,22,98,87,45,33,1,2,100]
Output:  [2, 1, 21, 22, 100, 10, 45, 87, 33, 98]


In [7]:
a = np.arrange(10)
print(a)
print(a.shape)
print (a.T.shape)


NameError: name 'np' is not defined

In [8]:
import numpy as np


In [10]:
a = np.arange(10)
print(a)
print(a.shape)
print (a.T.shape)

[0 1 2 3 4 5 6 7 8 9]
(10,)
(10,)


In [11]:
a = np.arange(10).reshape(2,5)
print(a)
print(a.T)
print(a.sum(axis = 1))
print(a.shape)
a.resize(5,5)
print(a)


[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]]
[10 35]
(2, 5)


ValueError: cannot resize this array: it does not own its data

In [12]:
a = np.arange(10)
print(a)
print(a.T)
print(a.sum(axis = 1))
print(a.shape)
a.resize(5,5)
print(a)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]


AxisError: axis 1 is out of bounds for array of dimension 1